# Define the goal
time initial_time # if zero => initial_time = ros::Time_now()
duration traj_duration
float64[] initial_position 
float64[] final_position
float64[] initial_velocity 
float64[] final_velocity
float64[] initial_acceleration 
float64[] final_acceleration
string[] joint_names
---
# Define the result
---
# Define a feedback message
float64 time_left